######################################################################
# GitLab CI build script for the docker-scala-sbt Docker image.      #
# The resulting image is used to build Scala based microservices     #
######################################################################
image: docker:latest

variables:
  DOCKER_DRIVER: overlay

services:
  - docker:dind

before_script:
  - echo "Running build $CI_BUILD_ID"
  - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json
  - docker info

stages:
  - build

build:
  stage: build
  script:
    - docker build -t $MUSIT_DOCKER_REGISTRY/musit/docker-node:latest .
    - docker push $MUSIT_DOCKER_REGISTRY/musit/docker-node:latest
